name: Youtube Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get dependencies
      run: sudo apt-get install libcurl4-openssl-dev
    - name: Checks
      working-directory: ./src/tests
      run: make tests
